// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsdqpqsnqkwvludobchu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzZHFwcXNucWt3dmx1ZG9iY2h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NzkyNDQsImV4cCI6MjA1ODQ1NTI0NH0.rlZ0qp8OA7CVUX8dDr4p2ZvCnN_MK6isRJaA8I0z0UY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);